
# Syntax highlighting
markdown:            kramdown
highlighter:         rouge

# Permalinks
permalink:           /:title
#relative_permalinks: true

# Setup
timezone:            Asia/Seoul # eg. Asia/Kathmandu
locale:              kr # eg. en_us
name:			     devwon's blog
title:               Devwon's blog
tagline:             'tagline'
description:         'description'
url:                 https://devwon.github.io
rss:                 https://blog.devwon.site
baseurl:             'https://devwon.github.io/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              devwon # get it on https://disqus.com/admin/

author:
  name:           	 devwon
  url:            	 https://devwon.github.io
  facebook:          username
  twitter:           username
  google_plus:       username
  linkedin:          hyerin-won-a2360a154
  dribbble:          username
  pinterest:         username
  kiva:              username

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
